namespace dbarone_api.Lib.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

/// <summary>
/// Denotes that the property is a DateTime / timestamp column.
/// </summary>
[AttributeUsage(AttributeTargets.Property, Inherited = true)]
public class AutoGeneratedAttribute : Attribute
{
    public string SequenceName { get; set; }
    public bool UseCurrentDateTime { get; set; }
    public bool UseCurrentUser { get; set; }
    public bool OnUpdate { get; set; }
    public bool OnInsert { get; set; }

    public AutoGeneratedAttribute(string sequenceName = null, bool useCurrentDateTime = false, bool useCurrentUser = false, bool onUpdate = false, bool onInsert = false)
    {
        this.SequenceName = sequenceName;
        this.UseCurrentDateTime = useCurrentDateTime;
        this.UseCurrentUser = useCurrentUser;
        this.OnUpdate = onUpdate;
        this.OnInsert = onInsert;
    }
}
